using BootstrapTagHelpers.Attributes;

namespace BootstrapTagHelpers {

    public enum Glyphicons {
        [DisplayValue("glyphicon-asterisk")]
        Asterisk,
        [DisplayValue("glyphicon-plus")]
        Plus,
        [DisplayValue("glyphicon-euro")]
        Euro,
        [DisplayValue("glyphicon-eur")]
        Eur,
        [DisplayValue("glyphicon-minus")]
        Minus,
        [DisplayValue("glyphicon-cloud")]
        Cloud,
        [DisplayValue("glyphicon-envelope")]
        Envelope,
        [DisplayValue("glyphicon-pencil")]
        Pencil,
        [DisplayValue("glyphicon-glass")]
        Glass,
        [DisplayValue("glyphicon-music")]
        Music,
        [DisplayValue("glyphicon-search")]
        Search,
        [DisplayValue("glyphicon-heart")]
        Heart,
        [DisplayValue("glyphicon-star")]
        Star,
        [DisplayValue("glyphicon-star-empty")]
        StarEmpty,
        [DisplayValue("glyphicon-user")]
        User,
        [DisplayValue("glyphicon-film")]
        Film,
        [DisplayValue("glyphicon-th-large")]
        ThLarge,
        [DisplayValue("glyphicon-th")]
        Th,
        [DisplayValue("glyphicon-th-list")]
        ThList,
        [DisplayValue("glyphicon-ok")]
        Ok,
        [DisplayValue("glyphicon-remove")]
        Remove,
        [DisplayValue("glyphicon-zoom-in")]
        ZoomIn,
        [DisplayValue("glyphicon-zoom-out")]
        ZoomOut,
        [DisplayValue("glyphicon-off")]
        Off,
        [DisplayValue("glyphicon-signal")]
        Signal,
        [DisplayValue("glyphicon-cog")]
        Cog,
        [DisplayValue("glyphicon-trash")]
        Trash,
        [DisplayValue("glyphicon-home")]
        Home,
        [DisplayValue("glyphicon-file")]
        File,
        [DisplayValue("glyphicon-time")]
        Time,
        [DisplayValue("glyphicon-road")]
        Road,
        [DisplayValue("glyphicon-download-alt")]
        DownloadAlt,
        [DisplayValue("glyphicon-download")]
        Download,
        [DisplayValue("glyphicon-upload")]
        Upload,
        [DisplayValue("glyphicon-inbox")]
        Inbox,
        [DisplayValue("glyphicon-play-circle")]
        PlayCircle,
        [DisplayValue("glyphicon-repeat")]
        Repeat,
        [DisplayValue("glyphicon-refresh")]
        Refresh,
        [DisplayValue("glyphicon-list-alt")]
        ListAlt,
        [DisplayValue("glyphicon-lock")]
        Lock,
        [DisplayValue("glyphicon-flag")]
        Flag,
        [DisplayValue("glyphicon-headphones")]
        Headphones,
        [DisplayValue("glyphicon-volume-off")]
        VolumeOff,
        [DisplayValue("glyphicon-volume-down")]
        VolumeDown,
        [DisplayValue("glyphicon-volume-up")]
        VolumeUp,
        [DisplayValue("glyphicon-qrcode")]
        Qrcode,
        [DisplayValue("glyphicon-barcode")]
        Barcode,
        [DisplayValue("glyphicon-tag")]
        Tag,
        [DisplayValue("glyphicon-tags")]
        Tags,
        [DisplayValue("glyphicon-book")]
        Book,
        [DisplayValue("glyphicon-bookmark")]
        Bookmark,
        [DisplayValue("glyphicon-print")]
        Print,
        [DisplayValue("glyphicon-camera")]
        Camera,
        [DisplayValue("glyphicon-font")]
        Font,
        [DisplayValue("glyphicon-bold")]
        Bold,
        [DisplayValue("glyphicon-italic")]
        Italic,
        [DisplayValue("glyphicon-text-height")]
        TextHeight,
        [DisplayValue("glyphicon-text-width")]
        TextWidth,
        [DisplayValue("glyphicon-align-left")]
        AlignLeft,
        [DisplayValue("glyphicon-align-center")]
        AlignCenter,
        [DisplayValue("glyphicon-align-right")]
        AlignRight,
        [DisplayValue("glyphicon-align-justify")]
        AlignJustify,
        [DisplayValue("glyphicon-list")]
        List,
        [DisplayValue("glyphicon-indent-left")]
        IndentLeft,
        [DisplayValue("glyphicon-indent-right")]
        IndentRight,
        [DisplayValue("glyphicon-facetime-video")]
        FacetimeVideo,
        [DisplayValue("glyphicon-picture")]
        Picture,
        [DisplayValue("glyphicon-map-marker")]
        MapMarker,
        [DisplayValue("glyphicon-adjust")]
        Adjust,
        [DisplayValue("glyphicon-tint")]
        Tint,
        [DisplayValue("glyphicon-edit")]
        Edit,
        [DisplayValue("glyphicon-share")]
        Share,
        [DisplayValue("glyphicon-check")]
        Check,
        [DisplayValue("glyphicon-move")]
        Move,
        [DisplayValue("glyphicon-step-backward")]
        StepBackward,
        [DisplayValue("glyphicon-fast-backward")]
        FastBackward,
        [DisplayValue("glyphicon-backward")]
        Backward,
        [DisplayValue("glyphicon-play")]
        Play,
        [DisplayValue("glyphicon-pause")]
        Pause,
        [DisplayValue("glyphicon-stop")]
        Stop,
        [DisplayValue("glyphicon-forward")]
        Forward,
        [DisplayValue("glyphicon-fast-forward")]
        FastForward,
        [DisplayValue("glyphicon-step-forward")]
        StepForward,
        [DisplayValue("glyphicon-eject")]
        Eject,
        [DisplayValue("glyphicon-chevron-left")]
        ChevronLeft,
        [DisplayValue("glyphicon-chevron-right")]
        ChevronRight,
        [DisplayValue("glyphicon-plus-sign")]
        PlusSign,
        [DisplayValue("glyphicon-minus-sign")]
        MinusSign,
        [DisplayValue("glyphicon-remove-sign")]
        RemoveSign,
        [DisplayValue("glyphicon-ok-sign")]
        OkSign,
        [DisplayValue("glyphicon-question-sign")]
        QuestionSign,
        [DisplayValue("glyphicon-info-sign")]
        InfoSign,
        [DisplayValue("glyphicon-screenshot")]
        Screenshot,
        [DisplayValue("glyphicon-remove-circle")]
        RemoveCircle,
        [DisplayValue("glyphicon-ok-circle")]
        OkCircle,
        [DisplayValue("glyphicon-ban-circle")]
        BanCircle,
        [DisplayValue("glyphicon-arrow-left")]
        ArrowLeft,
        [DisplayValue("glyphicon-arrow-right")]
        ArrowRight,
        [DisplayValue("glyphicon-arrow-up")]
        ArrowUp,
        [DisplayValue("glyphicon-arrow-down")]
        ArrowDown,
        [DisplayValue("glyphicon-share-alt")]
        ShareAlt,
        [DisplayValue("glyphicon-resize-full")]
        ResizeFull,
        [DisplayValue("glyphicon-resize-small")]
        ResizeSmall,
        [DisplayValue("glyphicon-exclamation-sign")]
        ExclamationSign,
        [DisplayValue("glyphicon-gift")]
        Gift,
        [DisplayValue("glyphicon-leaf")]
        Leaf,
        [DisplayValue("glyphicon-fire")]
        Fire,
        [DisplayValue("glyphicon-eye-open")]
        EyeOpen,
        [DisplayValue("glyphicon-eye-close")]
        EyeClose,
        [DisplayValue("glyphicon-warning-sign")]
        WarningSign,
        [DisplayValue("glyphicon-plane")]
        Plane,
        [DisplayValue("glyphicon-calendar")]
        Calendar,
        [DisplayValue("glyphicon-random")]
        Random,
        [DisplayValue("glyphicon-comment")]
        Comment,
        [DisplayValue("glyphicon-magnet")]
        Magnet,
        [DisplayValue("glyphicon-chevron-up")]
        ChevronUp,
        [DisplayValue("glyphicon-chevron-down")]
        ChevronDown,
        [DisplayValue("glyphicon-retweet")]
        Retweet,
        [DisplayValue("glyphicon-shopping-cart")]
        ShoppingCart,
        [DisplayValue("glyphicon-folder-close")]
        FolderClose,
        [DisplayValue("glyphicon-folder-open")]
        FolderOpen,
        [DisplayValue("glyphicon-resize-vertical")]
        ResizeVertical,
        [DisplayValue("glyphicon-resize-horizontal")]
        ResizeHorizontal,
        [DisplayValue("glyphicon-hdd")]
        Hdd,
        [DisplayValue("glyphicon-bullhorn")]
        Bullhorn,
        [DisplayValue("glyphicon-bell")]
        Bell,
        [DisplayValue("glyphicon-certificate")]
        Certificate,
        [DisplayValue("glyphicon-thumbs-up")]
        ThumbsUp,
        [DisplayValue("glyphicon-thumbs-down")]
        ThumbsDown,
        [DisplayValue("glyphicon-hand-right")]
        HandRight,
        [DisplayValue("glyphicon-hand-left")]
        HandLeft,
        [DisplayValue("glyphicon-hand-up")]
        HandUp,
        [DisplayValue("glyphicon-hand-down")]
        HandDown,
        [DisplayValue("glyphicon-circle-arrow-right")]
        CircleArrowRight,
        [DisplayValue("glyphicon-circle-arrow-left")]
        CircleArrowLeft,
        [DisplayValue("glyphicon-circle-arrow-up")]
        CircleArrowUp,
        [DisplayValue("glyphicon-circle-arrow-down")]
        CircleArrowDown,
        [DisplayValue("glyphicon-globe")]
        Globe,
        [DisplayValue("glyphicon-wrench")]
        Wrench,
        [DisplayValue("glyphicon-tasks")]
        Tasks,
        [DisplayValue("glyphicon-filter")]
        Filter,
        [DisplayValue("glyphicon-briefcase")]
        Briefcase,
        [DisplayValue("glyphicon-fullscreen")]
        Fullscreen,
        [DisplayValue("glyphicon-dashboard")]
        Dashboard,
        [DisplayValue("glyphicon-paperclip")]
        Paperclip,
        [DisplayValue("glyphicon-heart-empty")]
        HeartEmpty,
        [DisplayValue("glyphicon-link")]
        Link,
        [DisplayValue("glyphicon-phone")]
        Phone,
        [DisplayValue("glyphicon-pushpin")]
        Pushpin,
        [DisplayValue("glyphicon-usd")]
        Usd,
        [DisplayValue("glyphicon-gbp")]
        Gbp,
        [DisplayValue("glyphicon-sort")]
        Sort,
        [DisplayValue("glyphicon-sort-by-alphabet")]
        SortByAlphabet,
        [DisplayValue("glyphicon-sort-by-alphabet-alt")]
        SortByAlphabetAlt,
        [DisplayValue("glyphicon-sort-by-order")]
        SortByOrder,
        [DisplayValue("glyphicon-sort-by-order-alt")]
        SortByOrderAlt,
        [DisplayValue("glyphicon-sort-by-attributes")]
        SortByAttributes,
        [DisplayValue("glyphicon-sort-by-attributes-alt")]
        SortByAttributesAlt,
        [DisplayValue("glyphicon-unchecked")]
        Unchecked,
        [DisplayValue("glyphicon-expand")]
        Expand,
        [DisplayValue("glyphicon-collapse-down")]
        CollapseDown,
        [DisplayValue("glyphicon-collapse-up")]
        CollapseUp,
        [DisplayValue("glyphicon-log-in")]
        LogIn,
        [DisplayValue("glyphicon-flash")]
        Flash,
        [DisplayValue("glyphicon-log-out")]
        LogOut,
        [DisplayValue("glyphicon-new-window")]
        NewWindow,
        [DisplayValue("glyphicon-record")]
        Record,
        [DisplayValue("glyphicon-save")]
        Save,
        [DisplayValue("glyphicon-open")]
        Open,
        [DisplayValue("glyphicon-saved")]
        Saved,
        [DisplayValue("glyphicon-import")]
        Import,
        [DisplayValue("glyphicon-export")]
        Export,
        [DisplayValue("glyphicon-send")]
        Send,
        [DisplayValue("glyphicon-floppy-disk")]
        FloppyDisk,
        [DisplayValue("glyphicon-floppy-saved")]
        FloppySaved,
        [DisplayValue("glyphicon-floppy-remove")]
        FloppyRemove,
        [DisplayValue("glyphicon-floppy-save")]
        FloppySave,
        [DisplayValue("glyphicon-floppy-open")]
        FloppyOpen,
        [DisplayValue("glyphicon-credit-card")]
        CreditCard,
        [DisplayValue("glyphicon-transfer")]
        Transfer,
        [DisplayValue("glyphicon-cutlery")]
        Cutlery,
        [DisplayValue("glyphicon-header")]
        Header,
        [DisplayValue("glyphicon-compressed")]
        Compressed,
        [DisplayValue("glyphicon-earphone")]
        Earphone,
        [DisplayValue("glyphicon-phone-alt")]
        PhoneAlt,
        [DisplayValue("glyphicon-tower")]
        Tower,
        [DisplayValue("glyphicon-stats")]
        Stats,
        [DisplayValue("glyphicon-sd-video")]
        SdVideo,
        [DisplayValue("glyphicon-hd-video")]
        HdVideo,
        [DisplayValue("glyphicon-subtitles")]
        Subtitles,
        [DisplayValue("glyphicon-sound-stereo")]
        SoundStereo,
        [DisplayValue("glyphicon-sound-dolby")]
        SoundDolby,
        [DisplayValue("glyphicon-sound-5-1")]
        Sound51,
        [DisplayValue("glyphicon-sound-6-1")]
        Sound61,
        [DisplayValue("glyphicon-sound-7-1")]
        Sound71,
        [DisplayValue("glyphicon-copyright-mark")]
        CopyrightMark,
        [DisplayValue("glyphicon-registration-mark")]
        RegistrationMark,
        [DisplayValue("glyphicon-cloud-download")]
        CloudDownload,
        [DisplayValue("glyphicon-cloud-upload")]
        CloudUpload,
        [DisplayValue("glyphicon-tree-conifer")]
        TreeConifer,
        [DisplayValue("glyphicon-tree-deciduous")]
        TreeDeciduous,
        [DisplayValue("glyphicon-cd")]
        Cd,
        [DisplayValue("glyphicon-save-file")]
        SaveFile,
        [DisplayValue("glyphicon-open-file")]
        OpenFile,
        [DisplayValue("glyphicon-level-up")]
        LevelUp,
        [DisplayValue("glyphicon-copy")]
        Copy,
        [DisplayValue("glyphicon-paste")]
        Paste,
        [DisplayValue("glyphicon-alert")]
        Alert,
        [DisplayValue("glyphicon-equalizer")]
        Equalizer,
        [DisplayValue("glyphicon-king")]
        King,
        [DisplayValue("glyphicon-queen")]
        Queen,
        [DisplayValue("glyphicon-pawn")]
        Pawn,
        [DisplayValue("glyphicon-bishop")]
        Bishop,
        [DisplayValue("glyphicon-knight")]
        Knight,
        [DisplayValue("glyphicon-baby-formula")]
        BabyFormula,
        [DisplayValue("glyphicon-tent")]
        Tent,
        [DisplayValue("glyphicon-blackboard")]
        Blackboard,
        [DisplayValue("glyphicon-bed")]
        Bed,
        [DisplayValue("glyphicon-apple")]
        Apple,
        [DisplayValue("glyphicon-erase")]
        Erase,
        [DisplayValue("glyphicon-hourglass")]
        Hourglass,
        [DisplayValue("glyphicon-lamp")]
        Lamp,
        [DisplayValue("glyphicon-duplicate")]
        Duplicate,
        [DisplayValue("glyphicon-piggy-bank")]
        PiggyBank,
        [DisplayValue("glyphicon-scissors")]
        Scissors,
        [DisplayValue("glyphicon-bitcoin")]
        Bitcoin,
        [DisplayValue("glyphicon-btc")]
        Btc,
        [DisplayValue("glyphicon-xbt")]
        Xbt,
        [DisplayValue("glyphicon-yen")]
        Yen,
        [DisplayValue("glyphicon-jpy")]
        Jpy,
        [DisplayValue("glyphicon-ruble")]
        Ruble,
        [DisplayValue("glyphicon-rub")]
        Rub,
        [DisplayValue("glyphicon-scale")]
        Scale,
        [DisplayValue("glyphicon-ice-lolly")]
        IceLolly,
        [DisplayValue("glyphicon-ice-lolly-tasted")]
        IceLollyTasted,
        [DisplayValue("glyphicon-education")]
        Education,
        [DisplayValue("glyphicon-option-horizontal")]
        OptionHorizontal,
        [DisplayValue("glyphicon-option-vertical")]
        OptionVertical,
        [DisplayValue("glyphicon-menu-hamburger")]
        MenuHamburger,
        [DisplayValue("glyphicon-modal-window")]
        ModalWindow,
        [DisplayValue("glyphicon-oil")]
        Oil,
        [DisplayValue("glyphicon-grain")]
        Grain,
        [DisplayValue("glyphicon-sunglasses")]
        Sunglasses,
        [DisplayValue("glyphicon-text-size")]
        TextSize,
        [DisplayValue("glyphicon-text-color")]
        TextColor,
        [DisplayValue("glyphicon-text-background")]
        TextBackground,
        [DisplayValue("glyphicon-object-align-top")]
        ObjectAlignTop,
        [DisplayValue("glyphicon-object-align-bottom")]
        ObjectAlignBottom,
        [DisplayValue("glyphicon-object-align-horizontal")]
        ObjectAlignHorizontal,
        [DisplayValue("glyphicon-object-align-left")]
        ObjectAlignLeft,
        [DisplayValue("glyphicon-object-align-vertical")]
        ObjectAlignVertical,
        [DisplayValue("glyphicon-object-align-right")]
        ObjectAlignRight,
        [DisplayValue("glyphicon-triangle-right")]
        TriangleRight,
        [DisplayValue("glyphicon-triangle-left")]
        TriangleLeft,
        [DisplayValue("glyphicon-triangle-bottom")]
        TriangleBottom,
        [DisplayValue("glyphicon-triangle-top")]
        TriangleTop,
        [DisplayValue("glyphicon-console")]
        Console,
        [DisplayValue("glyphicon-superscript")]
        Superscript,
        [DisplayValue("glyphicon-subscript")]
        Subscript,
        [DisplayValue("glyphicon-menu-left")]
        MenuLeft,
        [DisplayValue("glyphicon-menu-right")]
        MenuRight,
        [DisplayValue("glyphicon-menu-down")]
        MenuDown,
        [DisplayValue("glyphicon-menu-up")]
        MenuUp
    }
}